### ISSUE TITLE
Remove dependencies?

### ISSUE THREAD

**Issue by etiennebacher** [extendr/b64#1]
Hi, that looks like a great example for making an `extendr`-powered package, thank you! 

I don't have a direct usecase for this but I suppose several other packages could use it under the hood. `base64enc` doesn't have any deps so I think this package could be more attractive by also having 0 dependencies, is this something you would consider?

From what I can see `rlang` and `cli` should be easy to remove, but `blob` brings several deps with it. Is `blob` really necessary?

**Comment by JosiahParry** [comment]
0 dependencies is really easy to accomplish. The current deps are fairly small hence why I felt comfortable with them. Otherwise, yah, it is really easy to make this a 0 dep package and we can do so no problem.

_howeverrrr...._ blob should definitely be a suggested package b/c blob is just `structure(list(), class = c("blob", "vctrs_list_of", "vctrs_vctr", "list" ))`. b64 doesn't need to have blob imported to assign the classes to a list object and the blob class makes for compatibility with data.frames otherwise it is just a list of raw vectors. 

Do you want to try adjusting it to be 0 dep for a 0.1.1 release?

**Comment by etiennebacher** [comment]
> Do you want to try adjusting it to be 0 dep for a 0.1.1 release?

Sure I can give it a try later today (might need help for the `blob` stuff though)

**Comment by JosiahParry** [comment]
Ya, no problem. One of the other reasons for choosing a blob was for type consistency. These functions should always return the same type. Since its not possible to return multiple raw vectors outside of a list, the functions should always return a list of raws (and in this case with the blob classes) 

One of the important places to change is here: 
https://github.com/extendr/b64/blob/97014ff065447622fc20e213bb54ad5215774a49/src/rust/src/lib.rs#L37

right now it requires that blob type be passed in. Instead of checking the class of the list, you can instead check the class of each element. If it doesn't inherit raw an NA can be returned. 

Setting the blob class is always done before the list is returned. That can probably remain since class is just an attribute and having it does not change the behavior of the list. It just gets a fancier print method when blob is imported. 

https://github.com/extendr/b64/blob/97014ff065447622fc20e213bb54ad5215774a49/src/rust/src/lib.rs#L169

Here is where blob is forcibly added to the NAMESPACE 
https://github.com/extendr/b64/blob/97014ff065447622fc20e213bb54ad5215774a49/R/b64-package.R#L2

I think that's about it
